
// import COVERVERLETTER from 'COVERVERLETTER.pdf'
// import COVERVERLETTER1 from 'COVERVERLETTER1.pdf'
// import COVERVERLETTER2 from 'COVERVERLETTER2.pdf'
// import COVERVERLETTER3 from 'COVERVERLETTER3.pdf'

// export default {COVERVERLETTER, COVERVERLETTER1, COVERVERLETTER2, COVERVERLETTER3}